/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab;

import ru.ifmo.se.pokemon.*;
import lab.moves.*;
import lab.pokemons.*;

public class Main {
    public static void main(String[] args) {
		Battle b = new Battle();
		Pokemon p1 = new Ursaring("Медведь", 5);
		Pokemon p2 = new Staryu("ЗвездаТаланта", 10);
		Pokemon p3 = new Espeon("СолевойСфинкс", 15);
		Pokemon p4 = new Venomoth("ЛетунУрод", 20);
		Pokemon p5 = new Venonat("КомокШерсти", 25);
		Pokemon p6 = new Ludicolo("ЖирныйКарлик", 15);
		b.addAlly(p1);
		b.addAlly(p3);
		b.addAlly(p5);
		b.addFoe(p2);
		b.addFoe(p4);
		b.addFoe(p6);
		b.go();
    }
}
